# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Néhémie Strupler
tagline:          My homepage
url:              https://github.com/N3h3mi3/n3h3mi3.github.io/
paginate:         1
baseurl:          https://raw.githubusercontent.com/N3h3mi3/n3h3mi3.github.io/master/
author:
  name:           Néhémie Strupler
  url:            https://example.com
  email:          strupler@unistra.fr
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/N3h3mi3/n3h3mi3.github.io/


# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from